/**
 * v2 — VALID_INPUT prover helper.
 *
 * The on-chain `lock_note` ix (post-v2) requires a Groth16 proof attesting:
 *   (a) the note exists in the Merkle tree at a known recent root,
 *   (b) its public mint + commitment and private positive-u64 amount agree,
 *   (c) the prover knows the spending key whose owner_commitment hashes into
 *       the note (i.e. is the actual owner).
 *
 * The proof itself is generated by the user (or any party with the note
 * opening + spending key), and relayed by the TEE to `lock_note`. This
 * helper bundles the inputs together and shells out to snarkjs.
 *
 * Mirrors the pattern in `valid_spend` prover invocations elsewhere in
 * tests/ — kept under `tests/helpers/` because the snarkjs shell-out is
 * test-side infrastructure (production wants an in-process WebAssembly
 * prover; see the TODO at the top of `snarkjs-prover.ts`).
 */

import { resolve } from "node:path";

import { type Groth16OnChainProof } from "../../src/idl/vault-client.js";
import { noteCommitmentV2, pubkeyToFrPair } from "../../src/utxo/note.js";
import { be32ToDec } from "./e2e-helpers.js";
import { snarkjsFullProve } from "./snarkjs-prover.js";
import { deriveNoteUseTag } from "../../src/utxo/note-use.js";
import { bn254ToBE32 } from "../../src/keys/key-generators.js";

/** Where the compiled VALID_INPUT artefacts live, relative to the repo root. */
const WASM_REL = "circuits/build/valid_input/circuit_js/circuit.wasm";
const ZKEY_REL = "circuits/build/valid_input/circuit_final.zkey";

/** A 20-level Merkle witness for the depth-20 vault tree. */
export interface MerkleWitnessFr20 {
  /** 20 sibling commitments along the leaf→root path (each a BN254 Fr bigint). */
  pathElements: bigint[];
  /** 20 boolean indices: 0 = sibling is on the right, 1 = sibling on the left. */
  pathIndices: number[];
}

export interface ValidInputProveParams {
  /** Repo root — used to resolve circuit blobs + the snarkjs CLI. */
  repoRoot: string;

  // ----- circuit private witnesses -----
  spendingKey: bigint;
  ownerCommitmentBlinding: bigint;
  /** v2: single inner_hash replacing the old (nonce, blindingR) pair. */
  innerHash: bigint;
  /** Private positive-u64 note amount. */
  amount: bigint;
  merkleWitness: MerkleWitnessFr20;

  // ----- circuit public inputs -----
  /** 32-byte mint pubkey (raw bytes, NOT a `PublicKey` wrapper). */
  tokenMint: Uint8Array;
  /** 32-byte big-endian Merkle root the proof is being generated against. */
  merkleRootBE: Uint8Array;
}

export interface ValidInputProveResult {
  proof: Groth16OnChainProof;
  /**
   * Public inputs in the EXACT byte layout the on-chain verifier consumes,
   * in circuit-declaration order:
   *   [merkleRoot, noteUseTag, tokenMint_lo, tokenMint_hi]
   * Each 32 bytes BE. Returned for assertion / debugging convenience.
   */
  publicInputsBE: Uint8Array[];
  /** The computed note commitment (32 bytes BE). PRIVATE to the circuit now —
   *  returned only so a caller can check the leaf it built. */
  noteCommitmentBE: Uint8Array;
  /** The note-use tag (32 bytes BE) — what `buildLockNoteInstruction` takes,
   *  and public input 1 of the proof. */
  noteUseTagBE: Uint8Array;
}

/**
 * Generate a VALID_INPUT proof.
 *
 * The caller is responsible for ensuring the supplied (mint, amount,
 * spendingKey, ownerCommitmentBlinding, innerHash) actually compose
 * into a note whose commitment is at the position the merkleWitness
 * traverses to `merkleRootBE`. If any of those disagree, snarkjs will fail
 * to find a witness and throw.
 */
export async function proveValidInput(
  args: ValidInputProveParams,
): Promise<ValidInputProveResult> {
  if (args.amount <= 0n || args.amount > 0xffff_ffff_ffff_ffffn) {
    throw new Error("VALID_INPUT amount must be a positive u64");
  }
  if (args.tokenMint.length !== 32) {
    throw new Error("tokenMint must be 32 bytes");
  }
  if (args.merkleRootBE.length !== 32) {
    throw new Error("merkleRootBE must be 32 bytes");
  }
  if (args.merkleWitness.pathElements.length !== 20) {
    throw new Error("merkleWitness.pathElements must be 20 entries");
  }
  if (args.merkleWitness.pathIndices.length !== 20) {
    throw new Error("merkleWitness.pathIndices must be 20 entries");
  }

  // Recompute the note commitment from the opening — also acts as a
  // self-test that the inputs at least produce *some* leaf.
  const ownerCommitmentBytes = await (async () => {
    const { ownerCommitment } = await import("../../src/utxo/note.js");
    return ownerCommitment(args.spendingKey, args.ownerCommitmentBlinding);
  })();
  const commitmentBE = await noteCommitmentV2({
    tokenMint: args.tokenMint,
    amount: args.amount,
    ownerCommitment: ownerCommitmentBytes,
    innerHash: args.innerHash,
  });

  const useTagBE = await deriveNoteUseTag(
    commitmentBE,
    bn254ToBE32(args.innerHash),
  );

  const [mintLo, mintHi] = pubkeyToFrPair(args.tokenMint);

  const inputs: Record<string, string | string[]> = {
    merkleRoot: be32ToDec(args.merkleRootBE),
    // The circuit's public handle. `noteCommitment` is now an INTERNAL signal
    // there, so passing it would be rejected as an unknown input.
    noteUseTag: be32ToDec(useTagBE),
    tokenMint: [mintLo.toString(), mintHi.toString()],
    amount: args.amount.toString(),
    spendingKey: args.spendingKey.toString(),
    ownerCommitmentBlinding: args.ownerCommitmentBlinding.toString(),
    innerHash: args.innerHash.toString(),
    merklePath: args.merkleWitness.pathElements.map((e) => e.toString()),
    merkleIndices: args.merkleWitness.pathIndices.map((i) => i.toString()),
  };

  const { proof, publicInputsBE } = snarkjsFullProve(inputs, {
    repoRoot: args.repoRoot,
    circuitWasmPath: resolve(args.repoRoot, WASM_REL),
    circuitZkeyPath: resolve(args.repoRoot, ZKEY_REL),
  });

  return {
    proof,
    publicInputsBE,
    noteCommitmentBE: commitmentBE,
    noteUseTagBE: useTagBE,
  };
}
