[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "DtSR7WELiAJMSMsPSLmDmA9ai5Q4715vooH8vderTvX7"

[programs.devnet]
vault = "DtSR7WELiAJMSMsPSLmDmA9ai5Q4715vooH8vderTvX7"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'use cargo test + npm test'"

[test.validator]
url = "https://api.devnet.solana.com"

[workspace]
members = ["programs/vault"]
