//! On-chain Groth16 verification wrapper + per-circuit VK constants.
//!
//! VK constants are auto-generated by `scripts/parse-vk-to-rust.js` from the
//! snarkjs `verification_key.json` output of the ceremony. Regenerate after
//! any circuit change.

pub mod verifier;
pub mod vk_match_batch_n16;
pub mod vk_valid_deposit;
pub mod vk_valid_input;
pub mod vk_valid_merge_k2;
pub mod vk_valid_merge_k4;
pub mod vk_valid_spend;

pub use verifier::{verify_groth16_proof, Groth16Proof};
