/**
 * Poseidon cross-environment parity: TypeScript (circomlibjs) must produce
 * the exact same byte output as Rust (light-poseidon) for all arities we use
 * in circuits (2, 3, 5, 6). If this ever diverges, proofs generated by one
 * side will fail verification on the other — funds can be permanently locked.
 */

import { describe, it, expect } from "vitest";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { existsSync } from "node:fs";

import { poseidonHashBytesBE } from "../src/utxo/note.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..");
const helper = resolve(repoRoot, "target/debug/examples/poseidon-hash");

function rustHash(arity: number, inputs: bigint[]): string {
  if (!existsSync(helper)) throw new Error("poseidon-hash helper missing");
  const args = [String(arity), ...inputs.map((b) => b.toString())];
  const res = spawnSync(helper, args, { encoding: "utf8" });
  if (res.status !== 0) throw new Error(res.stderr || "helper failed");
  return res.stdout.trim();
}

describe("Poseidon parity (circomlibjs vs light-poseidon)", () => {
  const available = existsSync(helper);
  const ait = (name: string, fn: () => Promise<void>) =>
    available ? it(name, fn) : it.skip(name, fn);

  ait("arity 2: simple small inputs", async () => {
    const ts = Buffer.from(await poseidonHashBytesBE([42n, 42n])).toString(
      "hex",
    );
    const rs = rustHash(2, [42n, 42n]);
    expect(ts).toBe(rs);
  });

  ait("arity 2: larger distinct inputs", async () => {
    const a = 1234567890123456789n;
    const b = 9876543210987654321n;
    const ts = Buffer.from(await poseidonHashBytesBE([a, b])).toString("hex");
    expect(ts).toBe(rustHash(2, [a, b]));
  });

  ait("arity 3: three inputs", async () => {
    const ins: bigint[] = [1n, 2n, 3n];
    const ts = Buffer.from(await poseidonHashBytesBE(ins)).toString("hex");
    expect(ts).toBe(rustHash(3, ins));
  });

  ait("arity 5: viewing-key pair hash shape", async () => {
    const ins: bigint[] = [100n, 200n, 300n, 400n, 500n];
    const ts = Buffer.from(await poseidonHashBytesBE(ins)).toString("hex");
    expect(ts).toBe(rustHash(5, ins));
  });

  ait("arity 6: note commitment shape", async () => {
    const ins: bigint[] = [1n, 2n, 3n, 4n, 5n, 6n];
    const ts = Buffer.from(await poseidonHashBytesBE(ins)).toString("hex");
    expect(ts).toBe(rustHash(6, ins));
  });
});
