/**
 * Cross-environment parity for the User Commitment formula.
 *
 * The TS `userCommitmentFromKeys()` must produce the same 32-byte hex as the
 * Rust `user_commitment_from_keys()`. If they diverge, the on-chain
 * VALID_WALLET_CREATE proof (generated by either side) will be rejected.
 */

import { describe, it, expect } from "vitest";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { existsSync } from "node:fs";

import { userCommitmentFromKeys } from "../src/keys/user-commitment.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..");
const helper = resolve(repoRoot, "target/debug/examples/user-commitment");

function rustHelper(
  rootHex: string,
  skDec: bigint,
  vkDec: bigint,
  r0: bigint,
  r1: bigint,
  r2: bigint,
): string {
  if (!existsSync(helper)) throw new Error("user-commitment helper missing");
  const res = spawnSync(
    helper,
    [
      rootHex,
      skDec.toString(),
      vkDec.toString(),
      r0.toString(),
      r1.toString(),
      r2.toString(),
    ],
    { encoding: "utf8" },
  );
  if (res.status !== 0) throw new Error(res.stderr || "helper failed");
  return res.stdout.trim();
}

describe("User commitment parity (TS vs Rust)", () => {
  const available = existsSync(helper);
  const ait = (name: string, fn: () => Promise<void>) =>
    available ? it(name, fn) : it.skip(name, fn);

  ait("matches on fixed inputs", async () => {
    const rootBytes = new Uint8Array(32);
    for (let i = 0; i < 32; i++) rootBytes[i] = (i * 7) & 0xff;
    const rootHex = Buffer.from(rootBytes).toString("hex");

    const sk = 12345678901234567890n;
    const vk = 98765432109876543210n;
    const r0 = 1n;
    const r1 = 2n;
    const r2 = 3n;

    const tsHex = Buffer.from(
      await userCommitmentFromKeys({
        rootKeyPubkey: rootBytes,
        spendingKey: sk,
        viewingKey: vk,
        r0,
        r1,
        r2,
      }),
    ).toString("hex");

    const rustHex = rustHelper(rootHex, sk, vk, r0, r1, r2);
    expect(tsHex).toBe(rustHex);
  });

  ait("matches across varied blinding factors", async () => {
    const rootBytes = new Uint8Array(32).fill(0x42);
    const rootHex = Buffer.from(rootBytes).toString("hex");
    const sk = 42n;
    const vk = 77n;

    for (const r0 of [1n, 100n, 999999n]) {
      for (const r1 of [2n, 101n]) {
        for (const r2 of [3n, 102n]) {
          const tsHex = Buffer.from(
            await userCommitmentFromKeys({
              rootKeyPubkey: rootBytes,
              spendingKey: sk,
              viewingKey: vk,
              r0,
              r1,
              r2,
            }),
          ).toString("hex");
          const rustHex = rustHelper(rootHex, sk, vk, r0, r1, r2);
          expect(tsHex).toBe(rustHex);
        }
      }
    }
  });
});
