//! Markdown report emitter. Reads from `RunMetrics` once at run
//! end and writes a self-contained `BENCHMARK.md`-style table.

use std::fmt::Write;
use std::time::Duration;

use crate::config::RunConfig;
use crate::metrics::{CounterSnapshot, RunMetrics};

pub struct ReportInputs<'a> {
    pub cfg: &'a RunConfig,
    pub metrics: &'a RunMetrics,
    pub elapsed: Duration,
}

/// Render a markdown report. Lock-acquiring async, but cheap —
/// runs once after the traders have stopped.
pub async fn render_markdown(inputs: ReportInputs<'_>) -> String {
    let counters = inputs.metrics.snapshot_counters();
    let submit_hist = inputs.metrics.submit_latency_us.lock().await;
    let cancel_hist = inputs.metrics.cancel_latency_us.lock().await;
    let _match_hist = inputs.metrics.match_latency_us.lock().await;

    let actual_rate = if inputs.elapsed.as_secs_f64() > 0.0 {
        counters.submits_total as f64 / inputs.elapsed.as_secs_f64()
    } else {
        0.0
    };

    let mut out = String::new();
    let _ = writeln!(out, "# nyx-tee-loadgen benchmark");
    let _ = writeln!(out);
    let _ = writeln!(out, "## Run configuration\n");
    let _ = writeln!(out, "| Param | Value |");
    let _ = writeln!(out, "|---|---|");
    let _ = writeln!(out, "| endpoint | `{}` |", inputs.cfg.endpoint);
    let _ = writeln!(out, "| traders | {} |", inputs.cfg.traders);
    let _ = writeln!(
        out,
        "| target rate (aggregate) | {:.1} orders/s |",
        inputs.cfg.aggregate_target_rate()
    );
    let _ = writeln!(out, "| duration | {}s |", inputs.cfg.duration_secs);
    let _ = writeln!(out, "| scenario | {:?} |", inputs.cfg.scenario);
    let _ = writeln!(out, "| symbol | `{}` |", inputs.cfg.symbol);
    let _ = writeln!(out, "| cancel_rate | {:.2} |", inputs.cfg.cancel_rate);
    let _ = writeln!(out, "| auth_mode | {:?} |", inputs.cfg.auth_mode);
    let _ = writeln!(out, "| oracle_twap | {} |", inputs.cfg.oracle_twap);
    let _ = writeln!(out, "| fee_rate_bps | {} |", inputs.cfg.fee_rate_bps);
    let _ = writeln!(out);

    let _ = writeln!(out, "## Throughput\n");
    let _ = writeln!(out, "| Metric | Value |");
    let _ = writeln!(out, "|---|---|");
    let _ = writeln!(out, "| elapsed | {:.2}s |", inputs.elapsed.as_secs_f64());
    let _ = writeln!(out, "| actual submit rate | {:.1} orders/s |", actual_rate);
    let _ = writeln!(
        out,
        "| target submit rate | {:.1} orders/s |",
        inputs.cfg.aggregate_target_rate()
    );
    let _ = writeln!(
        out,
        "| achieved/target ratio | {:.1}% |",
        100.0 * actual_rate / inputs.cfg.aggregate_target_rate().max(1e-9)
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "## Submit outcomes\n");
    let _ = writeln!(out, "{}", render_submit_table(&counters));
    let _ = writeln!(out);

    let _ = writeln!(out, "## Cancel outcomes\n");
    let _ = writeln!(out, "{}", render_cancel_table(&counters));
    let _ = writeln!(out);

    let _ = writeln!(out, "## Latency (ms)\n");
    let _ = writeln!(out, "| Stream | count | P50 | P95 | P99 | P99.9 | max |");
    let _ = writeln!(out, "|---|---|---|---|---|---|---|");
    write_hist_row(&mut out, "submit", &submit_hist);
    write_hist_row(&mut out, "cancel", &cancel_hist);
    // Match latency is empty until we wire GET /orders polling
    // (PR 4f.3 territory). The histogram is allocated so the
    // schema is stable; the row reports `count=0`.
    write_hist_row(&mut out, "match (TODO)", &_match_hist);
    let _ = writeln!(out);

    let _ = writeln!(
        out,
        "*Generated by `nyx-tee-loadgen`. See `docs/tee-architecture.md` §13.4 for design.*"
    );
    out
}

fn render_submit_table(c: &CounterSnapshot) -> String {
    let total = c.submits_total.max(1);
    format!(
        "| Outcome | Count | % |\n\
         |---|---|---|\n\
         | 2xx accepted | {} | {:.2}% |\n\
         | 4xx client error | {} | {:.2}% |\n\
         | ↳ 429 rate-limited | {} | {:.2}% |\n\
         | 5xx server error | {} | {:.2}% |\n\
         | network error | {} | {:.2}% |\n\
         | **success rate** | | **{:.2}%** |",
        c.submits_ok,
        pct(c.submits_ok, total),
        c.submits_4xx,
        pct(c.submits_4xx, total),
        c.submits_429,
        pct(c.submits_429, total),
        c.submits_5xx,
        pct(c.submits_5xx, total),
        c.submits_neterr,
        pct(c.submits_neterr, total),
        100.0 * c.submit_success_rate(),
    )
}

fn render_cancel_table(c: &CounterSnapshot) -> String {
    let total = c.cancels_total.max(1);
    format!(
        "| Outcome | Count | % |\n\
         |---|---|---|\n\
         | 2xx ok | {} | {:.2}% |\n\
         | 4xx | {} | {:.2}% |\n\
         | 5xx + net err | {} | {:.2}% |",
        c.cancels_ok,
        pct(c.cancels_ok, total),
        c.cancels_4xx,
        pct(c.cancels_4xx, total),
        c.cancels_5xx,
        pct(c.cancels_5xx, total),
    )
}

fn pct(num: u64, denom: u64) -> f64 {
    if denom == 0 {
        return 0.0;
    }
    100.0 * num as f64 / denom as f64
}

fn write_hist_row(out: &mut String, label: &str, h: &hdrhistogram::Histogram<u64>) {
    let count = h.len();
    if count == 0 {
        let _ = writeln!(out, "| {label} | 0 | — | — | — | — | — |");
        return;
    }
    let to_ms = |us: u64| us as f64 / 1000.0;
    let _ = writeln!(
        out,
        "| {label} | {} | {:.2} | {:.2} | {:.2} | {:.2} | {:.2} |",
        count,
        to_ms(h.value_at_quantile(0.50)),
        to_ms(h.value_at_quantile(0.95)),
        to_ms(h.value_at_quantile(0.99)),
        to_ms(h.value_at_quantile(0.999)),
        to_ms(h.max()),
    );
}
