//! Nyx dark pool — vault program (Phase 1).
//!
//! Responsibilities:
//!   - SPL token custody via per-mint PDA token accounts.
//!   - UTXO note Merkle tree (Poseidon2 over BN254, depth 20).
//!   - Nullifier set / consumed-notes set / note locks (all PDA-based).
//!   - Groth16 verification of VALID_WALLET_CREATE and VALID_SPEND proofs.
//!   - TEE-forced atomic settlement.
//!
//! Reference: Section 23.1 of darkpool_protocol_spec_v3_changed.md

use anchor_lang::prelude::*;

pub mod errors;
pub mod instructions;
pub mod merkle;
pub mod state;
pub mod zk;

// Anchor's `#[program]` macro looks up `crate::<submod>::__client_accounts_*`
// and similar helper modules. Re-exporting each instruction submodule at crate
// root lets the macro resolve everything correctly even though our source lives
// under `programs/vault/src/instructions/`.
pub use instructions::close_batch_validity_marker;
pub use instructions::create_wallet;
pub use instructions::deposit;
pub use instructions::initialize;
pub use instructions::lock_note;
pub use instructions::release_lock;
pub use instructions::reset_merkle_tree;
pub use instructions::rotate_root_key;
pub use instructions::set_protocol_config;
pub use instructions::set_tee_pubkey;
pub use instructions::tee_forced_settle;
pub use instructions::tee_forced_settle_batched;
pub use instructions::verify_match_batch;
pub use instructions::withdraw;

use instructions::*;
use zk::Groth16Proof;

declare_id!("C63vKvysCzX55PKraas4Wc22ijqjGJQdPC1mrzCFVWZx");

#[program]
pub mod vault {
    use super::*;

    /// Initialize the global `VaultConfig` singleton. One-time setup.
    pub fn initialize(
        ctx: Context<Initialize>,
        tee_pubkey: Pubkey,
        root_key: Pubkey,
    ) -> Result<()> {
        initialize::initialize_handler(ctx, tee_pubkey, root_key)
    }

    /// Rotate the Permission Group root key. Must be signed by the current
    /// root key (self-signature model — admin cannot override).
    pub fn rotate_root_key(ctx: Context<RotateRootKey>, new_root_key: Pubkey) -> Result<()> {
        rotate_root_key::rotate_root_key_handler(ctx, new_root_key)
    }

    /// Register a User Commitment via VALID_WALLET_CREATE proof.
    pub fn create_wallet(
        ctx: Context<CreateWallet>,
        commitment: [u8; 32],
        proof: Groth16Proof,
    ) -> Result<()> {
        create_wallet::create_wallet_handler(ctx, commitment, proof)
    }

    /// Deposit SPL tokens into the vault and insert a UTXO note commitment.
    /// v2: a single `inner_hash` replaces the old (nonce, blinding_r) pair.
    pub fn deposit(
        ctx: Context<Deposit>,
        amount: u64,
        owner_commitment: [u8; 32],
        inner_hash: [u8; 32],
    ) -> Result<()> {
        deposit::deposit_handler(ctx, amount, owner_commitment, inner_hash)
    }

    /// Withdraw tokens using a VALID_SPEND proof.
    pub fn withdraw(
        ctx: Context<Withdraw>,
        note_commitment: [u8; 32],
        nullifier: [u8; 32],
        merkle_root: [u8; 32],
        amount: u64,
        proof: Groth16Proof,
    ) -> Result<()> {
        withdraw::withdraw_handler(ctx, note_commitment, nullifier, merkle_root, amount, proof)
    }

    /// Lock a note to an order (TEE-only; v2 requires a VALID_INPUT proof
    /// generated by the note owner so the TEE cannot phantom-lock).
    #[allow(clippy::too_many_arguments)]
    pub fn lock_note(
        ctx: Context<LockNote>,
        note_commitment: [u8; 32],
        order_id: [u8; 16],
        expiry_slot: u64,
        amount: u64,
        token_mint: Pubkey,
        merkle_root: [u8; 32],
        proof: Groth16Proof,
    ) -> Result<()> {
        lock_note::lock_note_handler(
            ctx,
            note_commitment,
            order_id,
            expiry_slot,
            amount,
            token_mint,
            merkle_root,
            proof,
        )
    }

    /// Release an expired note lock.
    pub fn release_lock(ctx: Context<ReleaseLock>, note_commitment: [u8; 32]) -> Result<()> {
        release_lock::release_lock_handler(ctx, note_commitment)
    }

    /// Post-deployment governance setter for the protocol-fee fields of
    /// `VaultConfig`. Admin-only. Safe to call repeatedly (e.g. to rotate
    /// the protocol-owner commitment or change the fee rate).
    pub fn set_protocol_config(
        ctx: Context<SetProtocolConfig>,
        protocol_owner_commitment: [u8; 32],
        fee_rate_bps: u16,
    ) -> Result<()> {
        set_protocol_config::set_protocol_config_handler(
            ctx,
            protocol_owner_commitment,
            fee_rate_bps,
        )
    }

    /// Rotate `vault_config.tee_pubkey` to a new attested TEE signer.
    /// Admin-only. Needed whenever a fresh CVM boots with a new
    /// dstack-derived signer. Devnet-simplified — production rotation
    /// is multisig + attestation-gated (see `set_tee_pubkey.rs`).
    pub fn set_tee_pubkey(ctx: Context<SetTeePubkey>, new_tee_pubkey: Pubkey) -> Result<()> {
        set_tee_pubkey::set_tee_pubkey_handler(ctx, new_tee_pubkey)
    }

    /// v3.5 — verify a single Groth16 attesting VALID_CREATE +
    /// VALID_PRICE for ALL N matches in a batch. Writes a
    /// `BatchValidityMarker` PDA seeded by the proof's public input
    /// (the Merkle root over per-slot leaves). The N
    /// `tee_forced_settle_batched` txs that follow each carry a
    /// Merkle inclusion proof against this marker. See
    /// `instructions/verify_match_batch.rs`. Subsumes the legacy v3.1
    /// `verify_valid_create` + `verify_valid_price` ix pair, which
    /// were removed in Phase 1c-hard.
    pub fn verify_match_batch(
        ctx: Context<VerifyMatchBatch>,
        merkle_root: [u8; 32],
        expiry_slot: u64,
        proof: Groth16Proof,
    ) -> Result<()> {
        verify_match_batch::verify_match_batch_handler(ctx, merkle_root, expiry_slot, proof)
    }

    /// v3.5 — atomic TEE-forced settlement. Reads the batch's
    /// `BatchValidityMarker` (one per batch, keyed by Merkle root)
    /// and walks a depth-4 Merkle inclusion path to bind this
    /// specific match to it. The legacy v3.1 `tee_forced_settle` ix
    /// + its `ValidCreateMarker` / `ValidPriceMarker` per-match
    /// dependencies were removed in Phase 1c-hard.
    pub fn tee_forced_settle_batched(
        ctx: Context<TeeForcedSettleBatched>,
        payload: MatchResultPayload,
        match_index: u8,
        merkle_proof: [[u8; 32]; 4],
    ) -> Result<()> {
        tee_forced_settle_batched::tee_forced_settle_batched_handler(
            ctx,
            payload,
            match_index,
            merkle_proof,
        )
    }

    /// v3.5 — close a `BatchValidityMarker` PDA and refund its rent to
    /// `marker.payer`. Called by the matcher after all N matches in
    /// the batch have settled, or by anyone post-expiry as garbage
    /// collection. See instructions/close_batch_validity_marker.rs.
    pub fn close_batch_validity_marker(
        ctx: Context<CloseBatchValidityMarker>,
        merkle_root: [u8; 32],
    ) -> Result<()> {
        close_batch_validity_marker::close_batch_validity_marker_handler(ctx, merkle_root)
    }

    /// DEV-NET-ONLY: reset the Merkle tree to empty. Admin-gated. See
    /// instructions/reset_merkle_tree.rs for rationale + caveats.
    pub fn reset_merkle_tree(ctx: Context<ResetMerkleTree>) -> Result<()> {
        reset_merkle_tree::reset_merkle_tree_handler(ctx)
    }

    /// One-shot migration: realloc `VaultConfig` to the current Rust
    /// struct size. Run once per devnet deployment whenever a layout
    /// change (e.g. `ROOT_HISTORY_SIZE` bump) makes the existing PDA
    /// shorter than `size_of::<VaultConfig>()`. Admin-gated.
    pub fn realloc_vault_config(ctx: Context<ReallocVaultConfig>) -> Result<()> {
        realloc_vault_config::realloc_vault_config_handler(ctx)
    }
}
