//! Nyx dark pool — vault program (Phase 1).
//!
//! Responsibilities:
//!   - SPL token custody via per-mint PDA token accounts.
//!   - UTXO note Merkle tree (Poseidon2 over BN254, depth 20).
//!   - Nullifier set / consumed-notes set / note locks (all PDA-based).
//!   - Groth16 verification of VALID_WALLET_CREATE and VALID_SPEND proofs.
//!   - TEE-forced atomic settlement.
//!
//! Reference: Section 23.1 of darkpool_protocol_spec_v3_changed.md

use anchor_lang::prelude::*;

pub mod errors;
pub mod instructions;
pub mod merkle;
pub mod state;
pub mod zk;

// Anchor's `#[program]` macro looks up `crate::<submod>::__client_accounts_*`
// and similar helper modules. Re-exporting each instruction submodule at crate
// root lets the macro resolve everything correctly even though our source lives
// under `programs/vault/src/instructions/`.
pub use instructions::create_wallet;
pub use instructions::deposit;
pub use instructions::initialize;
pub use instructions::lock_note;
pub use instructions::release_lock;
pub use instructions::reset_merkle_tree;
pub use instructions::rotate_root_key;
pub use instructions::set_protocol_config;
pub use instructions::tee_forced_settle;
pub use instructions::verify_valid_create;
pub use instructions::withdraw;

use instructions::*;
use zk::Groth16Proof;

declare_id!("C63vKvysCzX55PKraas4Wc22ijqjGJQdPC1mrzCFVWZx");

#[program]
pub mod vault {
    use super::*;

    /// Initialize the global `VaultConfig` singleton. One-time setup.
    pub fn initialize(
        ctx: Context<Initialize>,
        tee_pubkey: Pubkey,
        root_key: Pubkey,
    ) -> Result<()> {
        initialize::initialize_handler(ctx, tee_pubkey, root_key)
    }

    /// Rotate the Permission Group root key. Must be signed by the current
    /// root key (self-signature model — admin cannot override).
    pub fn rotate_root_key(ctx: Context<RotateRootKey>, new_root_key: Pubkey) -> Result<()> {
        rotate_root_key::rotate_root_key_handler(ctx, new_root_key)
    }

    /// Register a User Commitment via VALID_WALLET_CREATE proof.
    pub fn create_wallet(
        ctx: Context<CreateWallet>,
        commitment: [u8; 32],
        proof: Groth16Proof,
    ) -> Result<()> {
        create_wallet::create_wallet_handler(ctx, commitment, proof)
    }

    /// Deposit SPL tokens into the vault and insert a UTXO note commitment.
    pub fn deposit(
        ctx: Context<Deposit>,
        amount: u64,
        owner_commitment: [u8; 32],
        nonce: [u8; 32],
        blinding_r: [u8; 32],
    ) -> Result<()> {
        deposit::deposit_handler(ctx, amount, owner_commitment, nonce, blinding_r)
    }

    /// Withdraw tokens using a VALID_SPEND proof.
    pub fn withdraw(
        ctx: Context<Withdraw>,
        note_commitment: [u8; 32],
        nullifier: [u8; 32],
        merkle_root: [u8; 32],
        amount: u64,
        proof: Groth16Proof,
    ) -> Result<()> {
        withdraw::withdraw_handler(ctx, note_commitment, nullifier, merkle_root, amount, proof)
    }

    /// Lock a note to an order (TEE-only; v2 requires a VALID_INPUT proof
    /// generated by the note owner so the TEE cannot phantom-lock).
    #[allow(clippy::too_many_arguments)]
    pub fn lock_note(
        ctx: Context<LockNote>,
        note_commitment: [u8; 32],
        order_id: [u8; 16],
        expiry_slot: u64,
        amount: u64,
        token_mint: Pubkey,
        merkle_root: [u8; 32],
        proof: Groth16Proof,
    ) -> Result<()> {
        lock_note::lock_note_handler(
            ctx,
            note_commitment,
            order_id,
            expiry_slot,
            amount,
            token_mint,
            merkle_root,
            proof,
        )
    }

    /// Release an expired note lock.
    pub fn release_lock(ctx: Context<ReleaseLock>, note_commitment: [u8; 32]) -> Result<()> {
        release_lock::release_lock_handler(ctx, note_commitment)
    }

    /// Post-deployment governance setter for the protocol-fee fields of
    /// `VaultConfig`. Admin-only. Safe to call repeatedly (e.g. to rotate
    /// the protocol-owner commitment or change the fee rate).
    pub fn set_protocol_config(
        ctx: Context<SetProtocolConfig>,
        protocol_owner_commitment: [u8; 32],
        fee_rate_bps: u16,
    ) -> Result<()> {
        set_protocol_config::set_protocol_config_handler(
            ctx,
            protocol_owner_commitment,
            fee_rate_bps,
        )
    }

    /// v3 — verify a VALID_CREATE Groth16 proof and write a marker PDA
    /// that the subsequent `tee_forced_settle` ix will consume. Lands as a
    /// separate tx (the settle tx is already near the 1232-byte cap).
    #[allow(clippy::too_many_arguments)]
    pub fn verify_valid_create(
        ctx: Context<VerifyValidCreate>,
        note_a_commitment: [u8; 32],
        note_b_commitment: [u8; 32],
        note_c_commitment: [u8; 32],
        note_d_commitment: [u8; 32],
        note_e_commitment: [u8; 32],
        note_f_commitment: [u8; 32],
        quote_mint: Pubkey,
        base_mint: Pubkey,
        base_amount: u64,
        quote_amount: u64,
        buyer_change_amt: u64,
        seller_change_amt: u64,
        buyer_fee_amt: u64,
        seller_fee_amt: u64,
        expiry_slot: u64,
        proof: Groth16Proof,
    ) -> Result<()> {
        verify_valid_create::verify_valid_create_handler(
            ctx,
            note_a_commitment,
            note_b_commitment,
            note_c_commitment,
            note_d_commitment,
            note_e_commitment,
            note_f_commitment,
            quote_mint,
            base_mint,
            base_amount,
            quote_amount,
            buyer_change_amt,
            seller_change_amt,
            buyer_fee_amt,
            seller_fee_amt,
            expiry_slot,
            proof,
        )
    }

    /// Atomic TEE-forced settlement.
    pub fn tee_forced_settle(
        ctx: Context<TeeForcedSettle>,
        payload: MatchResultPayload,
    ) -> Result<()> {
        tee_forced_settle::tee_forced_settle_handler(ctx, payload)
    }

    /// DEV-NET-ONLY: reset the Merkle tree to empty. Admin-gated. See
    /// instructions/reset_merkle_tree.rs for rationale + caveats.
    pub fn reset_merkle_tree(ctx: Context<ResetMerkleTree>) -> Result<()> {
        reset_merkle_tree::reset_merkle_tree_handler(ctx)
    }

    /// One-shot migration: realloc `VaultConfig` to the current Rust
    /// struct size. Run once per devnet deployment whenever a layout
    /// change (e.g. `ROOT_HISTORY_SIZE` bump) makes the existing PDA
    /// shorter than `size_of::<VaultConfig>()`. Admin-gated.
    pub fn realloc_vault_config(ctx: Context<ReallocVaultConfig>) -> Result<()> {
        realloc_vault_config::realloc_vault_config_handler(ctx)
    }
}
